# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_DifficultyEstimatorGLinux')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_DifficultyEstimatorGLinux')
    _DifficultyEstimatorGLinux = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_DifficultyEstimatorGLinux', [dirname(__file__)])
        except ImportError:
            import _DifficultyEstimatorGLinux
            return _DifficultyEstimatorGLinux
        try:
            _mod = imp.load_module('_DifficultyEstimatorGLinux', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _DifficultyEstimatorGLinux = swig_import_helper()
    del swig_import_helper
else:
    import _DifficultyEstimatorGLinux
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _DifficultyEstimatorGLinux.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _DifficultyEstimatorGLinux.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _DifficultyEstimatorGLinux.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _DifficultyEstimatorGLinux.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _DifficultyEstimatorGLinux.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _DifficultyEstimatorGLinux.SwigPyIterator_equal(self, x)

    def copy(self):
        return _DifficultyEstimatorGLinux.SwigPyIterator_copy(self)

    def next(self):
        return _DifficultyEstimatorGLinux.SwigPyIterator_next(self)

    def __next__(self):
        return _DifficultyEstimatorGLinux.SwigPyIterator___next__(self)

    def previous(self):
        return _DifficultyEstimatorGLinux.SwigPyIterator_previous(self)

    def advance(self, n):
        return _DifficultyEstimatorGLinux.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _DifficultyEstimatorGLinux.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _DifficultyEstimatorGLinux.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _DifficultyEstimatorGLinux.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _DifficultyEstimatorGLinux.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _DifficultyEstimatorGLinux.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _DifficultyEstimatorGLinux.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _DifficultyEstimatorGLinux.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _DifficultyEstimatorGLinux.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _DifficultyEstimatorGLinux.StringVector___nonzero__(self)

    def __bool__(self):
        return _DifficultyEstimatorGLinux.StringVector___bool__(self)

    def __len__(self):
        return _DifficultyEstimatorGLinux.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _DifficultyEstimatorGLinux.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _DifficultyEstimatorGLinux.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _DifficultyEstimatorGLinux.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _DifficultyEstimatorGLinux.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _DifficultyEstimatorGLinux.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _DifficultyEstimatorGLinux.StringVector___setitem__(self, *args)

    def pop(self):
        return _DifficultyEstimatorGLinux.StringVector_pop(self)

    def append(self, x):
        return _DifficultyEstimatorGLinux.StringVector_append(self, x)

    def empty(self):
        return _DifficultyEstimatorGLinux.StringVector_empty(self)

    def size(self):
        return _DifficultyEstimatorGLinux.StringVector_size(self)

    def swap(self, v):
        return _DifficultyEstimatorGLinux.StringVector_swap(self, v)

    def begin(self):
        return _DifficultyEstimatorGLinux.StringVector_begin(self)

    def end(self):
        return _DifficultyEstimatorGLinux.StringVector_end(self)

    def rbegin(self):
        return _DifficultyEstimatorGLinux.StringVector_rbegin(self)

    def rend(self):
        return _DifficultyEstimatorGLinux.StringVector_rend(self)

    def clear(self):
        return _DifficultyEstimatorGLinux.StringVector_clear(self)

    def get_allocator(self):
        return _DifficultyEstimatorGLinux.StringVector_get_allocator(self)

    def pop_back(self):
        return _DifficultyEstimatorGLinux.StringVector_pop_back(self)

    def erase(self, *args):
        return _DifficultyEstimatorGLinux.StringVector_erase(self, *args)

    def __init__(self, *args):
        this = _DifficultyEstimatorGLinux.new_StringVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _DifficultyEstimatorGLinux.StringVector_push_back(self, x)

    def front(self):
        return _DifficultyEstimatorGLinux.StringVector_front(self)

    def back(self):
        return _DifficultyEstimatorGLinux.StringVector_back(self)

    def assign(self, n, x):
        return _DifficultyEstimatorGLinux.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _DifficultyEstimatorGLinux.StringVector_resize(self, *args)

    def insert(self, *args):
        return _DifficultyEstimatorGLinux.StringVector_insert(self, *args)

    def reserve(self, n):
        return _DifficultyEstimatorGLinux.StringVector_reserve(self, n)

    def capacity(self):
        return _DifficultyEstimatorGLinux.StringVector_capacity(self)
    __swig_destroy__ = _DifficultyEstimatorGLinux.delete_StringVector
    __del__ = lambda self: None
StringVector_swigregister = _DifficultyEstimatorGLinux.StringVector_swigregister
StringVector_swigregister(StringVector)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _DifficultyEstimatorGLinux.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _DifficultyEstimatorGLinux.IntVector___nonzero__(self)

    def __bool__(self):
        return _DifficultyEstimatorGLinux.IntVector___bool__(self)

    def __len__(self):
        return _DifficultyEstimatorGLinux.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _DifficultyEstimatorGLinux.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _DifficultyEstimatorGLinux.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _DifficultyEstimatorGLinux.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _DifficultyEstimatorGLinux.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _DifficultyEstimatorGLinux.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _DifficultyEstimatorGLinux.IntVector___setitem__(self, *args)

    def pop(self):
        return _DifficultyEstimatorGLinux.IntVector_pop(self)

    def append(self, x):
        return _DifficultyEstimatorGLinux.IntVector_append(self, x)

    def empty(self):
        return _DifficultyEstimatorGLinux.IntVector_empty(self)

    def size(self):
        return _DifficultyEstimatorGLinux.IntVector_size(self)

    def swap(self, v):
        return _DifficultyEstimatorGLinux.IntVector_swap(self, v)

    def begin(self):
        return _DifficultyEstimatorGLinux.IntVector_begin(self)

    def end(self):
        return _DifficultyEstimatorGLinux.IntVector_end(self)

    def rbegin(self):
        return _DifficultyEstimatorGLinux.IntVector_rbegin(self)

    def rend(self):
        return _DifficultyEstimatorGLinux.IntVector_rend(self)

    def clear(self):
        return _DifficultyEstimatorGLinux.IntVector_clear(self)

    def get_allocator(self):
        return _DifficultyEstimatorGLinux.IntVector_get_allocator(self)

    def pop_back(self):
        return _DifficultyEstimatorGLinux.IntVector_pop_back(self)

    def erase(self, *args):
        return _DifficultyEstimatorGLinux.IntVector_erase(self, *args)

    def __init__(self, *args):
        this = _DifficultyEstimatorGLinux.new_IntVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _DifficultyEstimatorGLinux.IntVector_push_back(self, x)

    def front(self):
        return _DifficultyEstimatorGLinux.IntVector_front(self)

    def back(self):
        return _DifficultyEstimatorGLinux.IntVector_back(self)

    def assign(self, n, x):
        return _DifficultyEstimatorGLinux.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _DifficultyEstimatorGLinux.IntVector_resize(self, *args)

    def insert(self, *args):
        return _DifficultyEstimatorGLinux.IntVector_insert(self, *args)

    def reserve(self, n):
        return _DifficultyEstimatorGLinux.IntVector_reserve(self, n)

    def capacity(self):
        return _DifficultyEstimatorGLinux.IntVector_capacity(self)
    __swig_destroy__ = _DifficultyEstimatorGLinux.delete_IntVector
    __del__ = lambda self: None
IntVector_swigregister = _DifficultyEstimatorGLinux.IntVector_swigregister
IntVector_swigregister(IntVector)

class IntVectorVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVectorVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVectorVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _DifficultyEstimatorGLinux.IntVectorVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _DifficultyEstimatorGLinux.IntVectorVector___nonzero__(self)

    def __bool__(self):
        return _DifficultyEstimatorGLinux.IntVectorVector___bool__(self)

    def __len__(self):
        return _DifficultyEstimatorGLinux.IntVectorVector___len__(self)

    def __getslice__(self, i, j):
        return _DifficultyEstimatorGLinux.IntVectorVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _DifficultyEstimatorGLinux.IntVectorVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _DifficultyEstimatorGLinux.IntVectorVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _DifficultyEstimatorGLinux.IntVectorVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _DifficultyEstimatorGLinux.IntVectorVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _DifficultyEstimatorGLinux.IntVectorVector___setitem__(self, *args)

    def pop(self):
        return _DifficultyEstimatorGLinux.IntVectorVector_pop(self)

    def append(self, x):
        return _DifficultyEstimatorGLinux.IntVectorVector_append(self, x)

    def empty(self):
        return _DifficultyEstimatorGLinux.IntVectorVector_empty(self)

    def size(self):
        return _DifficultyEstimatorGLinux.IntVectorVector_size(self)

    def swap(self, v):
        return _DifficultyEstimatorGLinux.IntVectorVector_swap(self, v)

    def begin(self):
        return _DifficultyEstimatorGLinux.IntVectorVector_begin(self)

    def end(self):
        return _DifficultyEstimatorGLinux.IntVectorVector_end(self)

    def rbegin(self):
        return _DifficultyEstimatorGLinux.IntVectorVector_rbegin(self)

    def rend(self):
        return _DifficultyEstimatorGLinux.IntVectorVector_rend(self)

    def clear(self):
        return _DifficultyEstimatorGLinux.IntVectorVector_clear(self)

    def get_allocator(self):
        return _DifficultyEstimatorGLinux.IntVectorVector_get_allocator(self)

    def pop_back(self):
        return _DifficultyEstimatorGLinux.IntVectorVector_pop_back(self)

    def erase(self, *args):
        return _DifficultyEstimatorGLinux.IntVectorVector_erase(self, *args)

    def __init__(self, *args):
        this = _DifficultyEstimatorGLinux.new_IntVectorVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _DifficultyEstimatorGLinux.IntVectorVector_push_back(self, x)

    def front(self):
        return _DifficultyEstimatorGLinux.IntVectorVector_front(self)

    def back(self):
        return _DifficultyEstimatorGLinux.IntVectorVector_back(self)

    def assign(self, n, x):
        return _DifficultyEstimatorGLinux.IntVectorVector_assign(self, n, x)

    def resize(self, *args):
        return _DifficultyEstimatorGLinux.IntVectorVector_resize(self, *args)

    def insert(self, *args):
        return _DifficultyEstimatorGLinux.IntVectorVector_insert(self, *args)

    def reserve(self, n):
        return _DifficultyEstimatorGLinux.IntVectorVector_reserve(self, n)

    def capacity(self):
        return _DifficultyEstimatorGLinux.IntVectorVector_capacity(self)
    __swig_destroy__ = _DifficultyEstimatorGLinux.delete_IntVectorVector
    __del__ = lambda self: None
IntVectorVector_swigregister = _DifficultyEstimatorGLinux.IntVectorVector_swigregister
IntVectorVector_swigregister(IntVectorVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _DifficultyEstimatorGLinux.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _DifficultyEstimatorGLinux.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _DifficultyEstimatorGLinux.DoubleVector___bool__(self)

    def __len__(self):
        return _DifficultyEstimatorGLinux.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _DifficultyEstimatorGLinux.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _DifficultyEstimatorGLinux.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _DifficultyEstimatorGLinux.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _DifficultyEstimatorGLinux.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _DifficultyEstimatorGLinux.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _DifficultyEstimatorGLinux.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _DifficultyEstimatorGLinux.DoubleVector_pop(self)

    def append(self, x):
        return _DifficultyEstimatorGLinux.DoubleVector_append(self, x)

    def empty(self):
        return _DifficultyEstimatorGLinux.DoubleVector_empty(self)

    def size(self):
        return _DifficultyEstimatorGLinux.DoubleVector_size(self)

    def swap(self, v):
        return _DifficultyEstimatorGLinux.DoubleVector_swap(self, v)

    def begin(self):
        return _DifficultyEstimatorGLinux.DoubleVector_begin(self)

    def end(self):
        return _DifficultyEstimatorGLinux.DoubleVector_end(self)

    def rbegin(self):
        return _DifficultyEstimatorGLinux.DoubleVector_rbegin(self)

    def rend(self):
        return _DifficultyEstimatorGLinux.DoubleVector_rend(self)

    def clear(self):
        return _DifficultyEstimatorGLinux.DoubleVector_clear(self)

    def get_allocator(self):
        return _DifficultyEstimatorGLinux.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _DifficultyEstimatorGLinux.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _DifficultyEstimatorGLinux.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        this = _DifficultyEstimatorGLinux.new_DoubleVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _DifficultyEstimatorGLinux.DoubleVector_push_back(self, x)

    def front(self):
        return _DifficultyEstimatorGLinux.DoubleVector_front(self)

    def back(self):
        return _DifficultyEstimatorGLinux.DoubleVector_back(self)

    def assign(self, n, x):
        return _DifficultyEstimatorGLinux.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _DifficultyEstimatorGLinux.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _DifficultyEstimatorGLinux.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _DifficultyEstimatorGLinux.DoubleVector_reserve(self, n)

    def capacity(self):
        return _DifficultyEstimatorGLinux.DoubleVector_capacity(self)
    __swig_destroy__ = _DifficultyEstimatorGLinux.delete_DoubleVector
    __del__ = lambda self: None
DoubleVector_swigregister = _DifficultyEstimatorGLinux.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class Edge(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Edge, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Edge, name)
    __repr__ = _swig_repr
    __swig_setmethods__["s"] = _DifficultyEstimatorGLinux.Edge_s_set
    __swig_getmethods__["s"] = _DifficultyEstimatorGLinux.Edge_s_get
    if _newclass:
        s = _swig_property(_DifficultyEstimatorGLinux.Edge_s_get, _DifficultyEstimatorGLinux.Edge_s_set)
    __swig_setmethods__["_from"] = _DifficultyEstimatorGLinux.Edge__from_set
    __swig_getmethods__["_from"] = _DifficultyEstimatorGLinux.Edge__from_get
    if _newclass:
        _from = _swig_property(_DifficultyEstimatorGLinux.Edge__from_get, _DifficultyEstimatorGLinux.Edge__from_set)
    __swig_setmethods__["nxt"] = _DifficultyEstimatorGLinux.Edge_nxt_set
    __swig_getmethods__["nxt"] = _DifficultyEstimatorGLinux.Edge_nxt_get
    if _newclass:
        nxt = _swig_property(_DifficultyEstimatorGLinux.Edge_nxt_get, _DifficultyEstimatorGLinux.Edge_nxt_set)

    def __init__(self, s, arg3, nxt):
        this = _DifficultyEstimatorGLinux.new_Edge(s, arg3, nxt)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _DifficultyEstimatorGLinux.delete_Edge
    __del__ = lambda self: None
Edge_swigregister = _DifficultyEstimatorGLinux.Edge_swigregister
Edge_swigregister(Edge)
cvar = _DifficultyEstimatorGLinux.cvar
maxnode = cvar.maxnode

class DifficultyEstimator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DifficultyEstimator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DifficultyEstimator, name)
    __repr__ = _swig_repr
    __swig_setmethods__["item_freq"] = _DifficultyEstimatorGLinux.DifficultyEstimator_item_freq_set
    __swig_getmethods__["item_freq"] = _DifficultyEstimatorGLinux.DifficultyEstimator_item_freq_get
    if _newclass:
        item_freq = _swig_property(_DifficultyEstimatorGLinux.DifficultyEstimator_item_freq_get, _DifficultyEstimatorGLinux.DifficultyEstimator_item_freq_set)
    __swig_setmethods__["G"] = _DifficultyEstimatorGLinux.DifficultyEstimator_G_set
    __swig_getmethods__["G"] = _DifficultyEstimatorGLinux.DifficultyEstimator_G_get
    if _newclass:
        G = _swig_property(_DifficultyEstimatorGLinux.DifficultyEstimator_G_get, _DifficultyEstimatorGLinux.DifficultyEstimator_G_set)
    __swig_setmethods__["itemset_now"] = _DifficultyEstimatorGLinux.DifficultyEstimator_itemset_now_set
    __swig_getmethods__["itemset_now"] = _DifficultyEstimatorGLinux.DifficultyEstimator_itemset_now_get
    if _newclass:
        itemset_now = _swig_property(_DifficultyEstimatorGLinux.DifficultyEstimator_itemset_now_get, _DifficultyEstimatorGLinux.DifficultyEstimator_itemset_now_set)
    __swig_setmethods__["active_edge"] = _DifficultyEstimatorGLinux.DifficultyEstimator_active_edge_set
    __swig_getmethods__["active_edge"] = _DifficultyEstimatorGLinux.DifficultyEstimator_active_edge_get
    if _newclass:
        active_edge = _swig_property(_DifficultyEstimatorGLinux.DifficultyEstimator_active_edge_get, _DifficultyEstimatorGLinux.DifficultyEstimator_active_edge_set)

    def clear(self):
        return _DifficultyEstimatorGLinux.DifficultyEstimator_clear(self)

    def __init__(self, item_sets, item_freq, n_samples):
        this = _DifficultyEstimatorGLinux.new_DifficultyEstimator(item_sets, item_freq, n_samples)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def predict_easy(self, s):
        return _DifficultyEstimatorGLinux.DifficultyEstimator_predict_easy(self, s)

    def predict_and_add(self, s):
        return _DifficultyEstimatorGLinux.DifficultyEstimator_predict_and_add(self, s)
    __swig_destroy__ = _DifficultyEstimatorGLinux.delete_DifficultyEstimator
    __del__ = lambda self: None
DifficultyEstimator_swigregister = _DifficultyEstimatorGLinux.DifficultyEstimator_swigregister
DifficultyEstimator_swigregister(DifficultyEstimator)

# This file is compatible with both classic and new-style classes.


