# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_JobMatcherLinux')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_JobMatcherLinux')
    _JobMatcherLinux = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_JobMatcherLinux', [dirname(__file__)])
        except ImportError:
            import _JobMatcherLinux
            return _JobMatcherLinux
        try:
            _mod = imp.load_module('_JobMatcherLinux', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _JobMatcherLinux = swig_import_helper()
    del swig_import_helper
else:
    import _JobMatcherLinux
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _JobMatcherLinux.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _JobMatcherLinux.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _JobMatcherLinux.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _JobMatcherLinux.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _JobMatcherLinux.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _JobMatcherLinux.SwigPyIterator_equal(self, x)

    def copy(self):
        return _JobMatcherLinux.SwigPyIterator_copy(self)

    def next(self):
        return _JobMatcherLinux.SwigPyIterator_next(self)

    def __next__(self):
        return _JobMatcherLinux.SwigPyIterator___next__(self)

    def previous(self):
        return _JobMatcherLinux.SwigPyIterator_previous(self)

    def advance(self, n):
        return _JobMatcherLinux.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _JobMatcherLinux.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _JobMatcherLinux.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _JobMatcherLinux.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _JobMatcherLinux.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _JobMatcherLinux.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _JobMatcherLinux.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _JobMatcherLinux.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _JobMatcherLinux.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _JobMatcherLinux.StringVector___nonzero__(self)

    def __bool__(self):
        return _JobMatcherLinux.StringVector___bool__(self)

    def __len__(self):
        return _JobMatcherLinux.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _JobMatcherLinux.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _JobMatcherLinux.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _JobMatcherLinux.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _JobMatcherLinux.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _JobMatcherLinux.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _JobMatcherLinux.StringVector___setitem__(self, *args)

    def pop(self):
        return _JobMatcherLinux.StringVector_pop(self)

    def append(self, x):
        return _JobMatcherLinux.StringVector_append(self, x)

    def empty(self):
        return _JobMatcherLinux.StringVector_empty(self)

    def size(self):
        return _JobMatcherLinux.StringVector_size(self)

    def swap(self, v):
        return _JobMatcherLinux.StringVector_swap(self, v)

    def begin(self):
        return _JobMatcherLinux.StringVector_begin(self)

    def end(self):
        return _JobMatcherLinux.StringVector_end(self)

    def rbegin(self):
        return _JobMatcherLinux.StringVector_rbegin(self)

    def rend(self):
        return _JobMatcherLinux.StringVector_rend(self)

    def clear(self):
        return _JobMatcherLinux.StringVector_clear(self)

    def get_allocator(self):
        return _JobMatcherLinux.StringVector_get_allocator(self)

    def pop_back(self):
        return _JobMatcherLinux.StringVector_pop_back(self)

    def erase(self, *args):
        return _JobMatcherLinux.StringVector_erase(self, *args)

    def __init__(self, *args):
        this = _JobMatcherLinux.new_StringVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _JobMatcherLinux.StringVector_push_back(self, x)

    def front(self):
        return _JobMatcherLinux.StringVector_front(self)

    def back(self):
        return _JobMatcherLinux.StringVector_back(self)

    def assign(self, n, x):
        return _JobMatcherLinux.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _JobMatcherLinux.StringVector_resize(self, *args)

    def insert(self, *args):
        return _JobMatcherLinux.StringVector_insert(self, *args)

    def reserve(self, n):
        return _JobMatcherLinux.StringVector_reserve(self, n)

    def capacity(self):
        return _JobMatcherLinux.StringVector_capacity(self)
    __swig_destroy__ = _JobMatcherLinux.delete_StringVector
    __del__ = lambda self: None
StringVector_swigregister = _JobMatcherLinux.StringVector_swigregister
StringVector_swigregister(StringVector)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _JobMatcherLinux.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _JobMatcherLinux.IntVector___nonzero__(self)

    def __bool__(self):
        return _JobMatcherLinux.IntVector___bool__(self)

    def __len__(self):
        return _JobMatcherLinux.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _JobMatcherLinux.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _JobMatcherLinux.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _JobMatcherLinux.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _JobMatcherLinux.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _JobMatcherLinux.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _JobMatcherLinux.IntVector___setitem__(self, *args)

    def pop(self):
        return _JobMatcherLinux.IntVector_pop(self)

    def append(self, x):
        return _JobMatcherLinux.IntVector_append(self, x)

    def empty(self):
        return _JobMatcherLinux.IntVector_empty(self)

    def size(self):
        return _JobMatcherLinux.IntVector_size(self)

    def swap(self, v):
        return _JobMatcherLinux.IntVector_swap(self, v)

    def begin(self):
        return _JobMatcherLinux.IntVector_begin(self)

    def end(self):
        return _JobMatcherLinux.IntVector_end(self)

    def rbegin(self):
        return _JobMatcherLinux.IntVector_rbegin(self)

    def rend(self):
        return _JobMatcherLinux.IntVector_rend(self)

    def clear(self):
        return _JobMatcherLinux.IntVector_clear(self)

    def get_allocator(self):
        return _JobMatcherLinux.IntVector_get_allocator(self)

    def pop_back(self):
        return _JobMatcherLinux.IntVector_pop_back(self)

    def erase(self, *args):
        return _JobMatcherLinux.IntVector_erase(self, *args)

    def __init__(self, *args):
        this = _JobMatcherLinux.new_IntVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _JobMatcherLinux.IntVector_push_back(self, x)

    def front(self):
        return _JobMatcherLinux.IntVector_front(self)

    def back(self):
        return _JobMatcherLinux.IntVector_back(self)

    def assign(self, n, x):
        return _JobMatcherLinux.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _JobMatcherLinux.IntVector_resize(self, *args)

    def insert(self, *args):
        return _JobMatcherLinux.IntVector_insert(self, *args)

    def reserve(self, n):
        return _JobMatcherLinux.IntVector_reserve(self, n)

    def capacity(self):
        return _JobMatcherLinux.IntVector_capacity(self)
    __swig_destroy__ = _JobMatcherLinux.delete_IntVector
    __del__ = lambda self: None
IntVector_swigregister = _JobMatcherLinux.IntVector_swigregister
IntVector_swigregister(IntVector)

class IntVectorVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVectorVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVectorVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _JobMatcherLinux.IntVectorVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _JobMatcherLinux.IntVectorVector___nonzero__(self)

    def __bool__(self):
        return _JobMatcherLinux.IntVectorVector___bool__(self)

    def __len__(self):
        return _JobMatcherLinux.IntVectorVector___len__(self)

    def __getslice__(self, i, j):
        return _JobMatcherLinux.IntVectorVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _JobMatcherLinux.IntVectorVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _JobMatcherLinux.IntVectorVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _JobMatcherLinux.IntVectorVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _JobMatcherLinux.IntVectorVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _JobMatcherLinux.IntVectorVector___setitem__(self, *args)

    def pop(self):
        return _JobMatcherLinux.IntVectorVector_pop(self)

    def append(self, x):
        return _JobMatcherLinux.IntVectorVector_append(self, x)

    def empty(self):
        return _JobMatcherLinux.IntVectorVector_empty(self)

    def size(self):
        return _JobMatcherLinux.IntVectorVector_size(self)

    def swap(self, v):
        return _JobMatcherLinux.IntVectorVector_swap(self, v)

    def begin(self):
        return _JobMatcherLinux.IntVectorVector_begin(self)

    def end(self):
        return _JobMatcherLinux.IntVectorVector_end(self)

    def rbegin(self):
        return _JobMatcherLinux.IntVectorVector_rbegin(self)

    def rend(self):
        return _JobMatcherLinux.IntVectorVector_rend(self)

    def clear(self):
        return _JobMatcherLinux.IntVectorVector_clear(self)

    def get_allocator(self):
        return _JobMatcherLinux.IntVectorVector_get_allocator(self)

    def pop_back(self):
        return _JobMatcherLinux.IntVectorVector_pop_back(self)

    def erase(self, *args):
        return _JobMatcherLinux.IntVectorVector_erase(self, *args)

    def __init__(self, *args):
        this = _JobMatcherLinux.new_IntVectorVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _JobMatcherLinux.IntVectorVector_push_back(self, x)

    def front(self):
        return _JobMatcherLinux.IntVectorVector_front(self)

    def back(self):
        return _JobMatcherLinux.IntVectorVector_back(self)

    def assign(self, n, x):
        return _JobMatcherLinux.IntVectorVector_assign(self, n, x)

    def resize(self, *args):
        return _JobMatcherLinux.IntVectorVector_resize(self, *args)

    def insert(self, *args):
        return _JobMatcherLinux.IntVectorVector_insert(self, *args)

    def reserve(self, n):
        return _JobMatcherLinux.IntVectorVector_reserve(self, n)

    def capacity(self):
        return _JobMatcherLinux.IntVectorVector_capacity(self)
    __swig_destroy__ = _JobMatcherLinux.delete_IntVectorVector
    __del__ = lambda self: None
IntVectorVector_swigregister = _JobMatcherLinux.IntVectorVector_swigregister
IntVectorVector_swigregister(IntVectorVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _JobMatcherLinux.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _JobMatcherLinux.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _JobMatcherLinux.DoubleVector___bool__(self)

    def __len__(self):
        return _JobMatcherLinux.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _JobMatcherLinux.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _JobMatcherLinux.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _JobMatcherLinux.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _JobMatcherLinux.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _JobMatcherLinux.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _JobMatcherLinux.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _JobMatcherLinux.DoubleVector_pop(self)

    def append(self, x):
        return _JobMatcherLinux.DoubleVector_append(self, x)

    def empty(self):
        return _JobMatcherLinux.DoubleVector_empty(self)

    def size(self):
        return _JobMatcherLinux.DoubleVector_size(self)

    def swap(self, v):
        return _JobMatcherLinux.DoubleVector_swap(self, v)

    def begin(self):
        return _JobMatcherLinux.DoubleVector_begin(self)

    def end(self):
        return _JobMatcherLinux.DoubleVector_end(self)

    def rbegin(self):
        return _JobMatcherLinux.DoubleVector_rbegin(self)

    def rend(self):
        return _JobMatcherLinux.DoubleVector_rend(self)

    def clear(self):
        return _JobMatcherLinux.DoubleVector_clear(self)

    def get_allocator(self):
        return _JobMatcherLinux.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _JobMatcherLinux.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _JobMatcherLinux.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        this = _JobMatcherLinux.new_DoubleVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _JobMatcherLinux.DoubleVector_push_back(self, x)

    def front(self):
        return _JobMatcherLinux.DoubleVector_front(self)

    def back(self):
        return _JobMatcherLinux.DoubleVector_back(self)

    def assign(self, n, x):
        return _JobMatcherLinux.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _JobMatcherLinux.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _JobMatcherLinux.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _JobMatcherLinux.DoubleVector_reserve(self, n)

    def capacity(self):
        return _JobMatcherLinux.DoubleVector_capacity(self)
    __swig_destroy__ = _JobMatcherLinux.delete_DoubleVector
    __del__ = lambda self: None
DoubleVector_swigregister = _JobMatcherLinux.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class State(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, State, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, State, name)
    __repr__ = _swig_repr
    __swig_setmethods__["samp_id"] = _JobMatcherLinux.State_samp_id_set
    __swig_getmethods__["samp_id"] = _JobMatcherLinux.State_samp_id_get
    if _newclass:
        samp_id = _swig_property(_JobMatcherLinux.State_samp_id_get, _JobMatcherLinux.State_samp_id_set)
    __swig_setmethods__["salary"] = _JobMatcherLinux.State_salary_set
    __swig_getmethods__["salary"] = _JobMatcherLinux.State_salary_get
    if _newclass:
        salary = _swig_property(_JobMatcherLinux.State_salary_get, _JobMatcherLinux.State_salary_set)

    def __init__(self, sampid=0, salary=0):
        this = _JobMatcherLinux.new_State(sampid, salary)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _JobMatcherLinux.delete_State
    __del__ = lambda self: None
State_swigregister = _JobMatcherLinux.State_swigregister
State_swigregister(State)

class JobMatcher(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, JobMatcher, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, JobMatcher, name)
    __repr__ = _swig_repr

    def __init__(self, w, th, n_top, skill_list, salary):
        this = _JobMatcherLinux.new_JobMatcher(w, th, n_top, skill_list, salary)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def reset(self):
        return _JobMatcherLinux.JobMatcher_reset(self)

    def discount(self, n_cur, n_all):
        return _JobMatcherLinux.JobMatcher_discount(self, n_cur, n_all)

    def add(self, s):
        return _JobMatcherLinux.JobMatcher_add(self, s)

    def predict_salary(self, s):
        return _JobMatcherLinux.JobMatcher_predict_salary(self, s)

    def top_average_of_heap(self, Qs_tmp):
        return _JobMatcherLinux.JobMatcher_top_average_of_heap(self, Qs_tmp)

    def top_average(self):
        return _JobMatcherLinux.JobMatcher_top_average(self)
    __swig_destroy__ = _JobMatcherLinux.delete_JobMatcher
    __del__ = lambda self: None
JobMatcher_swigregister = _JobMatcherLinux.JobMatcher_swigregister
JobMatcher_swigregister(JobMatcher)

# This file is compatible with both classic and new-style classes.


